name: Deploy Production
on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        env:
          cache-name: cache-deps-and-artifacts
        with:
          path: |
            ~/.npm
            node_modules
            .cache
            public
          key: build-and-deploy-cache-deps-and-artifacts-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-and-deploy-cache-node_modules-

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js Depdendencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_CDA_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_CDA_ACCESS_TOKEN }}

      - name: Deploy
        run: npm run deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: ${{ github.sha }}
